apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  namespace: {{ .Values.global.namespace }}
type: Opaque
stringData:
  jwt-secret: {{ .Values.global.jwtSecret | quote }}
  db-password: {{ .Values.postgresql.auth.password | quote }}
  minio-access-key: {{ .Values.minio.auth.rootUser | quote }}
  minio-secret-key: {{ .Values.minio.auth.rootPassword | quote }}
